-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT('Y')
);

-- 2.
CREATE TABLE TB_CLASS_TYPE (
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY ADD CONSTRAINT TB_CAT_PK PRIMARY KEY(NAME);

-- 4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR(10)
                          MODIFY NAME VARCHAR(20);

-- 6.                          
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;                          
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;

-- 7.
ALTER TABLE TB_CATEGORY DROP CONSTRAINT TB_CAT_PK;
ALTER TABLE TB_CLASS_TYPE DROP CONSTRAINT SYS_C0011314;

ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(CATEGORY_NAME);
ALTER TABLE TB_CLASS_TYPE ADD CONSTRAINT PK_CLASS_TYPE_NO PRIMARY KEY(CLASS_TYPE_NO);

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;


-- 9.
ALTER TABLE TB_DEPARTMENT ADD FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);
ALTER TABLE TB_DEPARTMENT RENAME CONSTRAINT SYS_C0011323 TO FK_DEPARTMENT_CATEGORY;
-- 10.
GRANT CREATE VIEW TO WORKBOOK;

CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT;
SELECT * FROM VW_학생일반정보;

-- 11.
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO;

SELECT * FROM VW_지도면담
ORDER BY 2;

-- 12.
DROP VIEW VW_학과별학생수;
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(S.DEPARTMENT_NO) AS STUDENT_COUNT
    FROM TB_DEPARTMENT D
    JOIN TB_STUDENT S ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
    GROUP BY DEPARTMENT_NAME;    
SELECT * FROM "VW_학과별학생수";

-- 13. 
UPDATE VW_학생일반정보 SET STUDENT_NAME = '민경민' WHERE STUDENT_NO = 'A213046';

-- 14.
CREATE OR REPLACE VW_학생일반정보
AS STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT WITH READ ONLY;
    
-- 15.
SELECT S.*
FROM (SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(CLASS_NO) "누적수강생수(명)"
        FROM TB_CLASS 
        JOIN TB_GRADE USING(CLASS_NO)
        WHERE SUBSTR(TERM_NO, 1,4) >= 2005
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY "누적수강생수(명)" DESC) S
WHERE ROWNUM <=3;