-- 1. 
INSERT INTO TB_CLASS_TYPE(
    SELECT 01 AS class_type_no, '전공필수' AS class_type_name
    FROM DUAL
    UNION
    SELECT 02 AS class_type_no, '전공선택' AS class_type_name
    FROM DUAL
    UNION
    SELECT 03 AS class_type_no, '교양필수' AS class_type_name
    FROM DUAL
    UNION
    SELECT 04 AS class_type_no, '교양선택' AS class_type_name
    FROM DUAL
    UNION
    SELECT 05 AS class_type_no, '논문지도' AS class_type_name
    FROM DUAL
);

-- 2.

CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소 FROM TB_STUDENT;

-- 3. 
DROP TABLE TB_국어국문학과;
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1,6), 'RRMMDD'), 'RRRR') 출생년도, PROFESSOR_NAME 교수이름
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
    WHERE DEPARTMENT_NAME = '국어국문학과';
    
-- 4.
SELECT * FROM TB_DEPARTMENT;
UPDATE TB_DEPARTMENT SET CAPACITY = ROUND(CAPACITY*1.1);

-- 5.
UPDATE TB_STUDENT SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21' WHERE STUDENT_NO = 'A413042';
SELECT * FROM TB_STUDENT ;

-- 6.
UPDATE TB_STUDENT SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

-- 7.
UPDATE TB_GRADE SET POINT = 3.5 WHERE 


