-- 1. 
INSERT INTO TB_CLASS_TYPE(
    SELECT 01 AS class_type_no, '전공필수' AS class_type_name
    FROM DUAL
    UNION
    SELECT 02 AS class_type_no, '전공선택' AS class_type_name
    FROM DUAL
    UNION
    SELECT 03 AS class_type_no, '교양필수' AS class_type_name
    FROM DUAL
    UNION
    SELECT 04 AS class_type_no, '교양선택' AS class_type_name
    FROM DUAL
    UNION
    SELECT 05 AS class_type_no, '논문지도' AS class_type_name
    FROM DUAL
);

-- 2.

CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소 FROM TB_STUDENT;

-- 3. 
DROP TABLE TB_국어국문학과;    
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1,6), 'RRMMDD'), 'RRRR') 출생년도,  NVL(PROFESSOR_NAME, '지도교수없음')
    교수이름
    FROM TB_STUDENT S
    LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
    LEFT JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
    WHERE DEPARTMENT_NAME = '국어국문학과';
    
    SELECT * FROM TB_국어국문학과;
    SELECT * FROM TB_PROFESSOR WHERE DEPARTMENT_NO = 001;
    SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO = 001;
    
-- 4.
SELECT * FROM TB_DEPARTMENT;
UPDATE TB_DEPARTMENT SET CAPACITY = ROUND(CAPACITY*1.1);

-- 5.
UPDATE TB_STUDENT SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21' WHERE STUDENT_NO = 'A413042';
SELECT * FROM TB_STUDENT ;

-- 6.
UPDATE TB_STUDENT SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

-- 7.
UPDATE TB_GRADE SET POINT = 3.5 WHERE (STUDENT_NO, TERM_NO) = (
    SELECT STUDENT_NO, TERM_NO FROM TB_STUDENT
    JOIN TB_GRADE USING (STUDENT_NO)
    JOIN TB_CLASS USING (CLASS_NO)
    WHERE STUDENT_NAME = '김명훈' AND TERM_NO = 200501 AND CLASS_NAME = '피부생리학');

--8. 
DELETE FROM TB_GRADE WHERE STUDENT_NO IN (SELECT STUDENT_NO
    FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y');